stages:
  - build
  - publish

composer:
  stage: build
  image: php:7.3-cli
  before_script:
    - apt-get update
    - apt-get install -y git unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
  script:
    - php composer.phar install --no-progress --no-dev --optimize-autoloader
  cache:
    key: composer
    paths:
      - vendor/
  artifacts:
    paths:
      - vendor/

tarball:
  stage: publish
  image: alpine:latest
  script:
    - rm .gitlab-ci.yml
    - rm .gitignore
    - rm composer.*
    - rm -rf .git/
  artifacts:
    paths:
      - ./*
